### ISSUE TITLE
UCP: reattach containers to an overlay network

### ISSUE THREAD

**Issue by thebsdbox** [joeabbey/diver#97]
The code is already code to take a container and get it’s net info, and now the code to detach and then attach. This may alleviate some issues, thoughts @trapier

**Comment by trapier** [comment]
The only time I've needed to detach and re-attach a container is when taking a customer through the chemotherapy of intentional swarmkit cluster destruction, followed by UCP restore.  The containers involved are DTR, before cluster destruction, and after the `dtr-ol` overlay network has been manually recreated.  Issue this once on each of the DTR worker nodes:


```
docker ps -aq -f name=dtr |xargs -n1 docker network (dis)connect dtr-ol
```

Since it's a disaster recovery scenario, I'm not typically in the mindset of using the UCP API to put the containers back on the network, and depending on the scenario, swarmkit might not be functional enough for UCP to be working at that time anyway.

**Comment by thebsdbox** [comment]
Ah ok, 

I was under the impression it was a useful operation for containers that sometimes are in a connected (but aren't) situation.

Thanks @trapier
